name: '${name}'
main: '${group}.${name}'

bootstrapper: '${group}.bootstrap.CraftyLoader'

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'

dependencies:
  server:
    HeadDatabase:
      load: BEFORE
      required: false
      join-classpath: true